"""empty message

Revision ID: 6e6d9c75337d
Revises: d3bd8c48f329
Create Date: 2022-05-05 05:53:00.755916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6d9c75337d'
down_revision = 'd3bd8c48f329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('lat', sa.Numeric(precision=15, scale=10), nullable=True))
    op.add_column('listings', sa.Column('lng', sa.Numeric(precision=15, scale=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'lng')
    op.drop_column('listings', 'lat')
    # ### end Alembic commands ###
